project:
  type: website
  output-dir: docs

website:
  title: "Code You Can Bank On: Building, testing, and designing R packages"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: prereqs.html
        text: Prereqs
      - text: Materials
        menu:
        - text: ---
        - text: Building packages
        - text: ---
        - text: "Introduction"
          href: intro.html
        - text: "Package devopment"
          href: package-dev.html
        - text: ---
        - text: "Documentation"
          href: documentation.html
        - text: "Testing"
          href: testing.html
        - text: ---
        - text: "Design"
          href: design.html


format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

