project:
  type: website
  output-dir: docs

website:
  title: "Code You Can Bank On"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: prereqs.qmd
        text: Prereqs
      - text: Materials
        menu:
        - text: ---
        - text: Building packages
        - text: ---
        - text: "Introduction"
          href: intro.qmd
        - text: "Package devopment"
          href: package-dev.qmd
        - text: ---
        - text: "Documentation"
          href: documentation.qmd
        - text: "Testing"
          href: testing.qmd
        - text: ---
        - text: "Design"
          href: design.qmd


format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

