---
title: "Code You Can Bank On"
subtite: "Building, testing, and designing R packages"
editor: source
---

Materials for the Federal Reserve training August 10, 11, and 17

Led by Amelia McNamara, University of St Thomas

Topics: Package building, automated testing, designing code

Tentative schedule

  - August 10th
    - 9-10 am [intro, review](intro.qmd)
    - 10 am - 12 pm [package dev](package-dev.qmd)
    - 12-1 pm lunch break
    - 1-4 pm [documentation](documentation.qmd)
  - August 11th
  - 9 am - 11 am [testing](testing.qmd)
  - 11 am - 12 pm [design](design.qmd)
- August 17th
  - 9 am - 10 am [misc](misc.qmd)
  - 10 am - 12 pm [side effects](side-effects.qmd)
  - 12-1 pm lunch break
  - 1-2 pm [{testdat}](testdat.qmd)
  - 2-4 pm ? maybe [tidy eval](tidy-eval.qmd) or more data in packages?

    
    
All material is covered by a CC-BY-SA-4.0 license and source documents are [available on GitHub](https://github.com/AmeliaMN/CodeYouCanBankOn). 

The material here is in turn based on other CC-BY products, primarily [Building tidy tools workshop](https://github.com/rstudio-conf-2022/build-tidy-tools),  [uncoast::unconf day zero workshop](https://github.com/uncoast-unconf/uu-2019-day-zero), and [R packages book](https://r-pkgs.org/). 